[General]
bypass-system = true
skip-proxy = *.local, *.crashlytics.com
tun-excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12

[MITM]
hostname = api.revenuecat.com, buy.itunes.apple.com, api.picsart.com

[Script]
http-response ^https://api\.revenuecat\.com/.+/(receipts$|subscribers/[^/]+$) script-path=https://github.com/Win98Plus/Picsart-Premium-Shadowrocket/raw/refs/heads/main/PicsartUnlock.js, requires-body=true, timeout=5, tag=Crack
http-request https://api.picsart.com/gw-v2/shop/subscription/apple/purchases script-path=https://github.com/Win98Plus/Picsart-Premium-Shadowrocket/raw/refs/heads/main/Picsart.js, requires-body=true, timeout=5, tag=PicsArt
